### ISSUE TITLE
Authorization by password/etc

### ISSUE THREAD

**Issue by CakesTwix** [maksii/Toloka2Web#2]
I want to put it on the internet so that people I know can download new anime on Jellyfin

**Comment by maksii** [comment]
Перша версія буде доступна після мерджа пулла #4 . Перший зареєстрований користувач отримає роль адміна і доступ до сторінки налаштувань. Там же можна вимкнути реєстрацію, змінивши значення налаштування.

Але я б все ж таки рекомендував закриватися насамперед через реверспроксі або хоча б тим же гейтвеєм клаудфлеєра, а потім вже реєстрація.

**Comment by maksii** [comment]
Implemented in https://github.com/maksii/Toloka2Web/releases/tag/v2024.06.15
